baseURL = "https://yubrot.github.io/"
defaultContentLanguage = "en-us"
languageCode = "ja-jp"
theme = "tranquilpeak"
title = "yubrot.github.io"
# googleAnalytics = "UA-123-45"
canonifyurls = true

[permalinks]
post = "/:year/:month/:filename/"

[taxonomies]
archive = "archives"
category = "categories"
tag = "tags"

[author]
name = "yubrot"
# bio = ""
picture = "/images/yu.jpg"
twitter = "yubrot"

# [[menu.main]]
# identifier = "home"
# name = "Home"
# pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
# url = "/"
# weight = 1
[[menu.main]]
identifier = "profile"
name = "Profile"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-user\"></i>"
url = "/profile"
weight = 2
[[menu.main]]
identifier = "projects"
name = "Projects"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-diamond\"></i>"
url = "/categories/project"
weight = 3
# [[menu.main]]
# identifier = "archives"
# name = "Archives"
# pre = "<i class=\"sidebar-button-icon fa fa-lg fa-folder\"></i>"
# url = "/archives"
# weight = 4
# [[menu.main]]
# identifier = "tags"
# name = "Tags"
# pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
# url = "/tags"
# weight = 5

[[menu.links]]
identifier = "github"
name = "GitHub"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
url = "https://github.com/yubrot"
weight = 1
[[menu.links]]
identifier = "twitter"
name = "Twitter"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-twitter\"></i>"
url = "https://twitter.com/yubrot"
weight = 2
[[menu.links]]
identifier = "zenn"
name = "Zenn"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-code\"></i>"
url = "https://zenn.dev/yubrot"
weight = 3
[[menu.links]]
identifier = "scrapbox"
name = "Scrapbox"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-sticky-note\"></i>"
url = "https://scrapbox.io/yubrot"
weight = 4

[params]
autoThumbnailImage = true
clearReading = false
coverImage = "images/background.jpg"
hierarchicalCategories = false
sidebarBehavior = 1
swapPaginator = true
syntaxHighlighter = "highlight.js"
thumbnailImage = true
thumbnailImagePosition = "left"

[params.sidebar.profile]
url = "/"

[[params.sharingOptions]]
icon = "fa-twitter"
name = "Twitter"
url = "https://twitter.com/intent/tweet?text=%s"

[params.header.rightLink]
class = ""
icon = ""
url = "/profile"

[[params.customJS]]
crossorigin = "anonymous"
integrity = "sha384-YNHdsYkH6gMx9y3mRkmcJ2mFUjTd0qNQQvY9VYZgQd7DcN7env35GzlmFaZ23JGp"
src = "https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.js"

[[params.customJS]]
crossorigin = "anonymous"
integrity = "sha384-vZTG03m+2yp6N6BNi5iM4rW4oIwk5DfcNdFfxkk9ZWpDriOkXX8voJBFrAO7MpVl"
src = "https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/contrib/auto-render.min.js"

[[params.customJS]]
crossorigin = "anonymous"
integrity = "sha512-OowuWkXmzaarpYBk1sa79Vv/KEffTghmkzqG5g0eC+K0ujtoLpuvGzR3ED8YFST667Z5lQjnRsBObGq24m+mkQ=="
src = "https://cdnjs.cloudflare.com/ajax/libs/luminous-lightbox/2.3.3/Luminous.min.js"

[[params.customJS]]
src = "js/custom.js"

[[params.customCSS]]
crossorigin = "anonymous"
href = "https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.css"
integrity = "sha384-Um5gpz1odJg5Z4HAmzPtgZKdTBHZdw8S29IecapCSB31ligYPhHQZMIlWLYQGVoc"

[[params.customCSS]]
crossorigin = "anonymous"
href = "https://cdnjs.cloudflare.com/ajax/libs/luminous-lightbox/2.3.3/luminous-basic.min.css"
integrity = "sha512-qvPeSLkXsYxwQBnNswZ6Fri9TbDR2wOKSXzBFnuSFlOGbWob7KY8qrHU6F4YukwN6FmcdDWR1jYCbgWjf3nVkQ=="

[[params.customCSS]]
href = "css/custom.css"

[markup.goldmark.renderer]
hardWraps = true
